# Helm values for Falco
# Chart: falcosecurity/falco
# Repo:  https://falcosecurity.github.io/charts

driver:
  kind: modern_ebpf

collectors:
  kubernetes:
    enabled: true

falcosidekick:
  enabled: true
  webui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: falco.seancloud.org
          paths:
            - path: /
              pathType: Prefix
